### ISSUE TITLE
Consider using the "XDG Base Directory Specification" for the location of the configuration dir

### ISSUE THREAD

**Issue by andi-makes** [J0B10/JMacros#2]
The mentioned specification places configuration directories in specific locations defined by environment variables.
Currently, a lot of programs just litter the home directory with their configuration files/directories. 
By implementing this spec, all the configuration files/directories will be in one space. If the system doesn't have the required
environment variables, we can fall back to simply using the users home directory.

Further information about the spec:
 * [Specification](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)
 * [The arch wiki also has a great entry for this spec](https://wiki.archlinux.org/index.php/XDG_Base_Directory)

I would be happy to implement this feature if it is deemed desirable.

**Comment by J0B10** [comment]
👍 Looking forward to the pr
